### PR TITLE
Add prometheus metrics emitter

### PR DESCRIPTION
**Pull request by bluekeyes**
The core of this package is a `prometheus.Collector` implementation that exposes the metrics of an `rcrowley/go-metrics` registry. It also provides a convenience function for creating a collector, registering it with a Prometheus registry, and exposing it on a HTTP endpoint. If you need to customize any of the Prometheus options, you can use the Collector directly.

I ended up writing my own emitter because the existing exporters I found had some limitations:

* Don't understand our custom tag/label format
* Report at fixed intervals instead of implementing `Collector`
* Export histograms incorrectly

Because this is a new emitter, I tried to stay closer to Prometheus conventions rather than matching the Datadog emitter. Specifically:

* Some metrics have different names (e.g "mean" instead of "avg") to match the `go-metrics` terminology
* Timers are always exported in fractional seconds
* Medians are reported as the `0.5` quantile instead of as a separate named metric

But I could be convinced it's better to match the Datadog emitter for easier migration.

### CODE REVIEW

**Review by asvoboda — APPROVED** [review]
This seems pretty straightforward, thanks for implementing it! Do you think we should also add some basic functionality tests as well?

**Comment by bluekeyes** [comment]
Yeah, some basic tests would be good. I started writing some and discovered [an issue](https://github.com/prometheus/client_golang/issues/1308) with the Prometheus testing library, so I'm trying to decide how to best work around that.

**Comment by bluekeyes** [comment]
Updated to add tests. I also made some other changes:

* https://prometheus.io/docs/instrumenting/writing_exporters/ suggests not exporting statistics that you can calculate in Prometheus and specifically uses Dropwizard as an example, so I've removed most of those values.
* I added help text giving the original metric type. This was mostly to make the tests work, but might be useful.
* I added `seconds` to the name of all timer metrics
* The sanitize function replaces runs of invalid characters with a single underscore

**Review by asvoboda — APPROVED** [review]
LGTM

**Review by jamestoyer — APPROVED** [review]

**Pull request merged**
